# AUTEURS CALLS #
@base_URL =http://35.241.172.229:3000/api/authors
@authTokenMod=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmFhMmVkM2QwMDBiZGE4ODUyYmIiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjp0cnVlLCJpYXQiOjE2NzE2MjUzNzh9._eG5JnN87xm4QBAHYcRaWs3noUowx4AoOF5sgwnfdbY
@authTokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmE4MWVkM2QwMDBiZGE4ODUyYjkiLCJhZG1pbmlzdHJhdG9yIjp0cnVlLCJtb2RlcmF0b3IiOnRydWUsImlhdCI6MTY3MTYyNTM0NX0.VXXTjm7OfmqQl89vNkYJZozdSRQi_DYEsvEQTfnWPR4
@authTokenNone=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmFiZWVkM2QwMDBiZGE4ODUyYmQiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjpmYWxzZSwiaWF0IjoxNjcxNjI1NDA3fQ._kCcoqnS-EzT9HkBZWb0WpumN8GYBuOYt9dzfPlt0Y4
//willy Vandersteen
@objId1=63a2fb1ded3d000bda8852bf
//michel Weyland
@objId2=63a2fb71ed3d000bda8852c1


get {{base_URL}}

###

get {{base_URL}}/{{objId1}}
Content-Type: application/json

###

post {{base_URL}}
Content-Type: application/json
x-auth-token: {{authTokenAdmin}}

{
    "name":"Michel Weyland",
    "dateOfBirth":"19/08/1974"
}

###

put {{base_URL}}/{{objId2}}
Content-Type: application/json
x-auth-token: {{authTokenMod}}

{
    "name":"Michel Weyland",
    "dateOfBirth":"19/08/1947"
}

###

delete {{base_URL}}/{{objId2}}
Content-Type: application/json
x-auth-token: {{authTokenAdmin}}