# STRIPS CALLS #
@base_URL =http://35.241.172.229:3000/api/comics
@authTokenMod=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmFhMmVkM2QwMDBiZGE4ODUyYmIiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjp0cnVlLCJpYXQiOjE2NzE2MjUzNzh9._eG5JnN87xm4QBAHYcRaWs3noUowx4AoOF5sgwnfdbY
@authTokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmE4MWVkM2QwMDBiZGE4ODUyYjkiLCJhZG1pbmlzdHJhdG9yIjp0cnVlLCJtb2RlcmF0b3IiOnRydWUsImlhdCI6MTY3MTYyNTM0NX0.VXXTjm7OfmqQl89vNkYJZozdSRQi_DYEsvEQTfnWPR4
@authTokenNone=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmFiZWVkM2QwMDBiZGE4ODUyYmQiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjpmYWxzZSwiaWF0IjoxNjcxNjI1NDA3fQ._kCcoqnS-EzT9HkBZWb0WpumN8GYBuOYt9dzfPlt0Y4
@uitgever=depuis
@reeks=aria
@stripalbum=De vliegende aap
//de vliegende aap (strip)
@objID1=63a2fc4fed3d000bda8852d8
//de ring van de elflings (strip)
@objID2=63a2fc2aed3d000bda8852d1

get {{base_URL}}

###

get {{base_URL}}/{{objID1}}
Content-Type: application/json

###

get {{base_URL}}/title/{{stripalbum}}
Content-Type: application/json

###

get {{base_URL}}/series/{{reeks}}
Content-Type: application/json

###

get {{base_URL}}/publisher/{{uitgever}}
Content-Type: application/json

###

post {{base_URL}}
Content-Type: application/json
x-auth-token: {{authTokenMod}}

{
"title":"De vliegende aap",
"number":2,
"shortDescription":"-",
"seriesId":"63a2fb99ed3d000bda8852c4",
"authorId":"63a2fb1ded3d000bda8852bf",
"publisher":"Standaard Uitgeverij"
}

###

put {{base_URL}}/{{objID1}}
Content-Type: application/json
x-auth-token: {{authTokenMod}}

{
"title":"De omzwervingen van Aria",
"number":1,
"shortDescription":"-",
"seriesId":"63a2d70f7063753037f712ae",
"authorId":"63a2d52f38d7871a80d8b6d3",
"publisher":"Depuis"
}


###

delete {{base_URL}}/{{objID2}}
Content-Type: application/json
x-auth-token: {{authTokenAdmin}}