### USER CALLS ###
@base_URL=http://localhost:3000/api/users
@authTokenMod=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZDNkZTQ4N2RjYjcyNGI4MTQ2NTAiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjp0cnVlLCJpYXQiOjE2NzE2MTU0NTR9.vidjxb9OFZXbbEV35517ZgSOL-M7gJkekw84HIBWZ44
@authTokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZDQ1ZTQ4N2RjYjcyNGI4MTQ2NTMiLCJhZG1pbmlzdHJhdG9yIjp0cnVlLCJtb2RlcmF0b3IiOmZhbHNlLCJpYXQiOjE2NzE2MTU1ODJ9.qjmtQhPXYRqacDuxrA9ONUdC4kCk47xnEHO7nb4MJJA
@authTokenNone=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZDQ5ZTQ4N2RjYjcyNGI4MTQ2NTYiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjpmYWxzZSwiaWF0IjoxNjcxNjE1NjQ2fQ.r0wxxhhj2DeoZCuULrHyV9XzMnrV8k0dCAtxvKuwaWQ

POST {{base_URL}}
Content-Type: application/json

{
    "username": "Blayze",
    "email":"Blayze@mail.com",
    "password":"Blayze/1234",
    "administrator":false,
    "moderator":false
}

###

get {{base_URL}}/me
Content-Type: application/json
//x-auth-token: {{authTokenMod}}
//x-auth-token: {{authTokenAdmin}}
x-auth-token: {{authTokenNone}}