# STRIPS CALLS #
@base_URL =http://localhost:3000/api/comics
@authTokenMod=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZDNkZTQ4N2RjYjcyNGI4MTQ2NTAiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjp0cnVlLCJpYXQiOjE2NzE2MTU0NTR9.vidjxb9OFZXbbEV35517ZgSOL-M7gJkekw84HIBWZ44
@authTokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZDQ1ZTQ4N2RjYjcyNGI4MTQ2NTMiLCJhZG1pbmlzdHJhdG9yIjp0cnVlLCJtb2RlcmF0b3IiOmZhbHNlLCJpYXQiOjE2NzE2MTU1ODJ9.qjmtQhPXYRqacDuxrA9ONUdC4kCk47xnEHO7nb4MJJA
@authTokenNone=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZDQ5ZTQ4N2RjYjcyNGI4MTQ2NTYiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjpmYWxzZSwiaWF0IjoxNjcxNjE1NjQ2fQ.r0wxxhhj2DeoZCuULrHyV9XzMnrV8k0dCAtxvKuwaWQ
@uitgever=depuis
@auteur=merho
@reeks=aria
@stripalbum=De vliegende aap
@objID1=63a2da35332cb4aca637eba3
@objID2=63a2d9346c5f2248bc54b710

get {{base_URL}}

###

get {{base_URL}}/{{objID1}}
Content-Type: application/json

###

get {{base_URL}}/title/{{stripalbum}}
Content-Type: application/json

###

get {{base_URL}}/series/{{reeks}}
Content-Type: application/json

###

get {{base_URL}}/publisher/{{uitgever}}
Content-Type: application/json

###

post {{base_URL}}
Content-Type: application/json
x-auth-token: {{authTokenMod}}

{
"title":"De omzwervingen van ARIA",
"number":1,
"shortDescription":"-",
"seriesId":"63a2d70f7063753037f712ae",
"authorId":"63a2d52f38d7871a80d8b6d3",
"publisher":"Depuis"
}

###

put {{base_URL}}/{{objID1}}
Content-Type: application/json
x-auth-token: {{authTokenMod}}

{
"title":"De omzwervingen van Aria",
"number":1,
"shortDescription":"-",
"seriesId":"63a2d70f7063753037f712ae",
"authorId":"63a2d52f38d7871a80d8b6d3",
"publisher":"Depuis"
}


###

delete {{base_URL}}/{{objID2}}
Content-Type: application/json
x-auth-token: {{authTokenAdmin}}