### REEKSEN CALLS ###
@base_URL =http://35.241.172.229:3000/api/series
@authTokenMod=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmFhMmVkM2QwMDBiZGE4ODUyYmIiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjp0cnVlLCJpYXQiOjE2NzE2MjUzNzh9._eG5JnN87xm4QBAHYcRaWs3noUowx4AoOF5sgwnfdbY
@authTokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmE4MWVkM2QwMDBiZGE4ODUyYjkiLCJhZG1pbmlzdHJhdG9yIjp0cnVlLCJtb2RlcmF0b3IiOnRydWUsImlhdCI6MTY3MTYyNTM0NX0.VXXTjm7OfmqQl89vNkYJZozdSRQi_DYEsvEQTfnWPR4
@authTokenNone=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EyZmFiZWVkM2QwMDBiZGE4ODUyYmQiLCJhZG1pbmlzdHJhdG9yIjpmYWxzZSwibW9kZXJhdG9yIjpmYWxzZSwiaWF0IjoxNjcxNjI1NDA3fQ._kCcoqnS-EzT9HkBZWb0WpumN8GYBuOYt9dzfPlt0Y4
@uitgever=standaard uitgeverij
@auteur=willy
@reeks=aria
//suske en wiske
@object1=63a2fb99ed3d000bda8852c4
//aria
@object2=63a2fbdbed3d000bda8852c8

get {{base_URL}}

###

get {{base_URL}}/{{object1}}
Content-Type: application/json

###

get {{base_URL}}/name/{{reeks}}
Content-Type: application/json

###

get {{base_URL}}/author/{{auteur}}
Content-Type: application/json

###

post {{base_URL}}
Content-Type: application/json
x-auth-token: {{authTokenMod}}

{
    "name":"aria",
    "yearPublished":"1980",
    "authorId":"63a2fb71ed3d000bda8852c1"
}

###

put {{base_URL}}/{{object1}}
Content-Type: application/json
x-auth-token: {{authTokenMod}}

{
    "name":"Aria",
    "yearPublished":"1980",
    "authorId":"63a2d52f38d7871a80d8b6d3"
}

###

delete {{base_URL}}/{{object2}}
Content-Type: application/json
x-auth-token: {{authTokenAdmin}}
